[project]
name = "dbt-transformations"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dbt-bigquery>=1.9.1",
    "dbt-core>=1.9.1",
]
